# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-16 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='full_runner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=50)),
                ('last_name', models.CharField(default=None, max_length=50)),
                ('age', models.IntegerField(default=None)),
                ('gender', models.CharField(choices=[('M', 'ชาย'), ('F', 'หญิง')], default=None, max_length=1)),
                ('shirt_size', models.CharField(choices=[('S', 'S ขนาดรอบอก 38 นิ้ว'), ('M', 'M ขนาดรอบอก 40 นิ้ว'), ('L', 'L ขนาดรอบอก 42 นิ้ว'), ('XL', 'XL ขนาดรอบอก 44 นิ้ว')], default=None, max_length=2)),
                ('team', models.CharField(default=None, max_length=50)),
                ('address', models.CharField(default=None, max_length=250)),
                ('mobile', models.CharField(default=None, max_length=10)),
                ('send', models.CharField(choices=[('EVENT', 'รับหน้างาน'), ('EMS', 'ส่ง EMS')], default=None, max_length=5)),
                ('status', models.CharField(choices=[('รอตรวจสอบ', 'Pending'), ('ลงทะเบียนสำเร็จ', 'Approved'), ('มีปัญหา', 'Problem')], default='รอตรวจสอบ', max_length=20)),
                ('capture', models.FileField(default=None, upload_to='slip/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='half_runner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=50)),
                ('last_name', models.CharField(default=None, max_length=50)),
            ],
        ),
    ]
