# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-16 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='full_runner',
            name='capture',
            field=models.FileField(default=None, upload_to='slip/'),
        ),
    ]
