# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-16 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20171116_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='half_runner',
            name='address',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='half_runner',
            name='age',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='half_runner',
            name='capture',
            field=models.FileField(default=None, upload_to='slip/'),
        ),
        migrations.AddField(
            model_name='half_runner',
            name='gender',
            field=models.CharField(choices=[('M', 'ชาย'), ('F', 'หญิง')], default=None, max_length=1),
        ),
        migrations.AddField(
            model_name='half_runner',
            name='mobile',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='half_runner',
            name='send',
            field=models.CharField(choices=[('EVENT', 'รับหน้างาน'), ('EMS', 'ส่ง EMS')], default=None, max_length=5),
        ),
        migrations.AddField(
            model_name='half_runner',
            name='shirt_size',
            field=models.CharField(choices=[('S', 'S ขนาดรอบอก 38 นิ้ว'), ('M', 'M ขนาดรอบอก 40 นิ้ว'), ('L', 'L ขนาดรอบอก 42 นิ้ว'), ('XL', 'XL ขนาดรอบอก 44 นิ้ว')], default=None, max_length=2),
        ),
        migrations.AddField(
            model_name='half_runner',
            name='status',
            field=models.CharField(choices=[('รอตรวจสอบ', 'Pending'), ('ลงทะเบียนสำเร็จ', 'Approved'), ('มีปัญหา', 'Problem')], default='รอตรวจสอบ', max_length=20),
        ),
        migrations.AddField(
            model_name='half_runner',
            name='team',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
